name: Checkout
on: [push]

# we can use the files from our repository in a runner by fetching them from our repo inside the runner 
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files after checkout
        run: ls -a